name: Profile rolling stats

on:
  schedule:
    - cron: "17 5 * * *"   # daily
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/profile-stats.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compute stats and write Shields endpoint JSON
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            fs.mkdirSync('badges', { recursive: true });

            const login = 'Koen-Vannisselroij';
            const WINDOW_DAYS = 30;

            const to = new Date();
            const from = new Date(to.getTime() - WINDOW_DAYS * 24 * 60 * 60 * 1000);

            const q = `
              query($login:String!, $from:DateTime!, $to:DateTime!) {
                user(login: $login) {
                  contributionsCollection(from: $from, to: $to) {
                    totalCommitContributions
                    totalPullRequestContributions
                    totalIssueContributions
                    totalPullRequestReviewContributions
                  }
                }
              }
            `;

            const { user } = await github.graphql(q, {
              login,
              from: from.toISOString(),
              to: to.toISOString()
            });

            const cc = user.contributionsCollection;
            const days = WINDOW_DAYS;

            const commitAvg = (cc.totalCommitContributions / days).toFixed(2);
            const allContribs = cc.totalCommitContributions +
                                cc.totalPullRequestContributions +
                                cc.totalIssueContributions +
                                cc.totalPullRequestReviewContributions;
            const contribAvg = (allContribs / days).toFixed(2);

            const mkBadge = (label, message, color='blue', cacheSeconds=21600) => ({
              schemaVersion: 1, label, message, color, cacheSeconds
            });

            fs.writeFileSync('badges/commit-avg-30d.json',
              JSON.stringify(mkBadge('30d commit avg', `${commitAvg}/day`, 'blue')));
            fs.writeFileSync('badges/contrib-avg-30d.json',
              JSON.stringify(mkBadge('30d contributions avg', `${contribAvg}/day`, 'blue')));
            console.log({ commitAvg, contribAvg });

      - name: Commit and push badge JSON
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add badges/*.json
          git commit -m "chore: update profile badges" || echo "no changes to commit"
          git push
