name: Profile rolling stats

on:
  schedule:
    - cron: "17 5 * * *"   # daily
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "badges/**"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compute stats and write Shields endpoint JSON
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            fs.mkdirSync('badges', { recursive: true });

            const login = 'Koen-Vannisselroij';
            const WINDOW_DAYS = 30;

            const to = new Date();
            const from = new Date(to.getTime() - WINDOW_DAYS * 24 * 60 * 60 * 1000);

            const q = `
              query($login:String!, $from:DateTime!, $to:DateTime!) {
                user(login: $login) {
                  contributionsCollection(from: $from, to: $to) {
                    totalCommitContributions
                    totalPullRequestContributions
                    totalIssueContributions
                    totalPullRequestReviewContributions
                  }
                }
              }
            `;

            const { user } = await github.graphql(q, {
              login,
              from: from.toISOString(),
              to: to.toISOString()
            });

            const cc = user.contributionsCollection;
            const days = WINDOW_DAYS;

            const commitAvg = (cc.totalCommitContributions / days).toFixed(2);
            const allContribs = cc.totalCommitContributions +
                                cc.totalPullRequestContributions +
                                cc.totalIssueContributions +
                                cc.totalPullRequestReviewContributions;
            const contribAvg = (allContribs / days).toFixed(2);

            const mkBadge = (label, message, color='blue', cacheSeconds=21600) => ({
              schemaVersion: 1, label, message, color, cacheSeconds
            });

            fs.writeFileSync('badges/commit-avg-30d.json',
              JSON.stringify(mkBadge('30d commit avg', `${commitAvg}/day`, 'blue')));
            fs.writeFileSync('badges/contrib-avg-30d.json',
              JSON.stringify(mkBadge('30d contributions avg', `${contribAvg}/day`, 'blue')));
            // Also render a simple SVG "card" for last-30d stats
            const commits = cc.totalCommitContributions;
            const prs = cc.totalPullRequestContributions;
            const issues = cc.totalIssueContributions;
            const reviews = cc.totalPullRequestReviewContributions;

            const width = 640, height = 160, padX = 24;
            const colWidth = 140; // 4 columns
            const labels = [
              { label: 'Commits', value: String(commits) },
              { label: 'PRs', value: String(prs) },
              { label: 'Issues', value: String(issues) },
              { label: 'Reviews', value: String(reviews) },
            ];

            const col = (i) => padX + i * colWidth;
            const rows = labels.map((d, i) => `
              <g transform="translate(${col(i)}, 56)">
                <text class="label" x="0" y="14">${d.label}</text>
                <text class="value" x="0" y="44">${d.value}</text>
              </g>
            `).join('\n');

            const svg = `<?xml version="1.0" encoding="UTF-8"?>
            <svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">
              <style>
                .title { font: 600 18px 'Segoe UI', Ubuntu, Sans-Serif; fill: #24292f; }
                .label { font: 600 12px 'Segoe UI', Ubuntu, Sans-Serif; fill: #57606a; }
                .value { font: 700 28px 'Segoe UI', Ubuntu, Sans-Serif; fill: #0969da; }
                .muted { font: 600 12px 'Segoe UI', Ubuntu, Sans-Serif; fill: #57606a; }
              </style>
              <rect width="100%" height="100%" rx="10" fill="#fff" stroke="#e1e4e8"/>
              <text class="title" x="${padX}" y="32">GitHub Stats — Last 30 days</text>
              ${rows}
              <text class="muted" x="${padX}" y="128">Contribs/day: ${contribAvg} • Commits/day: ${commitAvg}</text>
            </svg>`;

            fs.writeFileSync('badges/last-30d-stats.svg', svg);
            console.log({ commitAvg, contribAvg, commits, prs, issues, reviews });

            // Overwrite with a more polished design
            {
              const width = 740, height = 190, padX = 28, padY = 22;
              const colWidth = 170; // 4 columns layout
              const updated = new Date().toISOString().slice(0, 10);
              const stats = [
                { label: 'Commits', value: commits },
                { label: 'PRs', value: prs },
                { label: 'Issues', value: issues },
                { label: 'Reviews', value: reviews },
              ];
              const cols = stats.map((d, i) => `
                <g transform="translate(${padX + i * colWidth}, ${padY + 52})">
                  <rect x="-8" y="-4" width="140" height="60" rx="8" fill="#161b22" stroke="#30363d" />
                  <text class="label" x="0" y="14">${d.label}</text>
                  <text class="value" x="0" y="44">${d.value}</text>
                </g>
              `).join('\n');
              const svg2 = `<?xml version="1.0" encoding="UTF-8"?>
              <svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">
                <defs>
                  <linearGradient id="acc" x1="0" y1="0" x2="1" y2="1">
                    <stop offset="0%" stop-color="#1f6feb"/>
                    <stop offset="100%" stop-color="#58a6ff"/>
                  </linearGradient>
                  <filter id="shadow" x="-10%" y="-10%" width="120%" height="120%">
                    <feDropShadow dx="0" dy="2" stdDeviation="2" flood-color="#000" flood-opacity="0.08"/>
                  </filter>
                </defs>
                <style>
                  .title { font: 700 20px 'Segoe UI', Ubuntu, Sans-Serif; fill: #c9d1d9; }
                  .subtitle { font: 600 12px 'Segoe UI', Ubuntu, Sans-Serif; fill: #8b949e; }
                  .label { font: 600 12px 'Segoe UI', Ubuntu, Sans-Serif; fill: #8b949e; }
                  .value { font: 800 28px 'Segoe UI', Ubuntu, Sans-Serif; fill: #58a6ff; }
                  .meta { font: 600 12px 'Segoe UI', Ubuntu, Sans-Serif; fill: #8b949e; }
                </style>
                <rect width="100%" height="100%" rx="14" fill="#0d1117" stroke="#30363d" filter="url(#shadow)"/>
                <rect x="${padX}" y="${padY - 8}" width="260" height="8" rx="4" fill="url(#acc)"/>
                <text class="title" x="${padX}" y="${padY + 24}">GitHub Stats — Last 30 days</text>
                ${cols}
                <text class="meta" x="${padX}" y="${height - 24}">Contribs/day: ${contribAvg} • Commits/day: ${commitAvg} • Updated: ${updated}</text>
              </svg>`;
              fs.writeFileSync('badges/last-30d-stats.svg', svg2);
            }

      - name: Commit and push badge assets
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add badges/*.json badges/*.svg
          git commit -m "chore: update profile badges" || echo "no changes to commit"
          git push
